env: debug
api_groups:
  http_bind: ":9220"
  mysql:
    address: "127.0.0.1:3306"
    username: "root"
    password: "123456"
  redis:
    address: "127.0.0.1:6379"
    password: "123456"
    database: 0
trigger_groups:
  crontab_setting: "*/1 1-22 * * *"
  restart: true
