env: debug
api_groups:
  http_bind: ":9220"
  mysql:
    address: "127.0.0.1:3306"
    username: "root"
    password: "123456"
    database: "user"
trigger_groups:
  crontab_setting: "*/1 1-22 * * *"
  restart: true
